#!/usr/bin/env bash
# Transfers file from our client to a server

FPATH=$1
SRVIP=$2
USER=$3
PKEYPATH=$4

if [[ $# -lt 3 ]]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
 scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
done
