#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page

new_strings="\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo apt-get update
sudo apt-get -y install nginx
echo 'Hello World' | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "24 i $new_strings" /etc/nginx/sites-available/default
sudo service nginx restart
