#!/usr/bin/env bash
# Make nginx run and listen on port 80 of all the server's active IPv4 IPs

sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
