#!/usr/bin/env bash
# This script is same as script 4 with added display when receiving SIGTERM

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap "echo I am invincible!!!" SIGTERM

done
