#!/usr/bin/env bash
# This script gives info about the file named school

F=school

if [ -e "$F" ]
then
    echo "school file exists"
    if [ -s "$F" ]
    then
        echo "school file is not empty"
    elif [ -f "$F" ]
    then
        echo "school file is a regular file"
    else
        echo "school file is empty"
    fi
else
    echo "school file does not exist"
fi
