#!/usr/bin/env bash
# Container runs Ngnix as the nginx user
# nginx listens on all active IPs on port 8080

chown nginx:nginx /etc/nginx/nginx.conf
sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
