#!/usr/bin/env bash
# Container runs Ngnix as the nginx user
# nginx listens on all active IPs on port 8080

sudo pkill apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
