#!/usr/bin/env bash
# Container runs Ngnix as the nginx user
# nginx listens on all active IPs on port 8080

sudo pkill -o apache2
sudo chmod 755 /etc/nginx/nginx.conf
sudo sed -i 's/#user www-data;/user ngix;/' /etc/nginx/nginx.conf
sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
